services:
  app:
    build: .
    container_name: spil-ijin-kerja-app
    restart: always
    environment:
      - PORT=3000
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_PATH=/app/ijin-kerja
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      # Public & Internal HTTP Router
      - "traefik.http.routers.spil-ijin-kerja-http.rule=(Host(`px.spil.co.id`) || Host(`pe.spil.co.id`)) && PathPrefix(`/app/ijin-kerja`)"
      - "traefik.http.routers.spil-ijin-kerja-http.entrypoints=web"
      - "traefik.http.routers.spil-ijin-kerja-http.service=spil-ijin-kerja-svc"

      # Public & Internal HTTPS Router
      - "traefik.http.routers.spil-ijin-kerja-https.rule=(Host(`px.spil.co.id`) || Host(`pe.spil.co.id`)) && PathPrefix(`/app/ijin-kerja`)"
      - "traefik.http.routers.spil-ijin-kerja-https.entrypoints=websecure"
      - "traefik.http.routers.spil-ijin-kerja-https.tls=true"
      - "traefik.http.routers.spil-ijin-kerja-https.service=spil-ijin-kerja-svc"

      # Load Balancer Service Port
      - "traefik.http.services.spil-ijin-kerja-svc.loadbalancer.server.port=3000"
    volumes:
      - ./spil_permits.db:/app/spil_permits.db
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
